navigationListeningPort: 11111
TMCListeningPort: 12222
v2xAppListeningPort: 15000
simulationDirectory: /home/szezso/V2X-Simulation-with-SUMO/simulation/
mapSaveConfig:
    namePattern: yyyy-MM-dd HH:mm:ss.SSS
    saveDir: saved_maps/
    saveFile: netFiles.dat